---
name: 荒らし連合軍
description: 荒らし連合の公式サイトです。
url: https://aarr-jp.github.io
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
defaults:
- scope:
    path: ''
  values:
    image: "/assets/images/site-image.png"